[package]
name = "RustingBrain"
version = "0.1.0"
edition = "2024"

[dependencies]
matrixmultiply = "0.3.10"
rand = { version = "0.8", features = ["std"] }
rayon = "1.11.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
